name: Download from Localazy
on:
  workflow_dispatch:

jobs:
  localazy-download:
    name: Download strings from Localazy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}

      - name: Download Localazy
        uses: localazy/download@v1
        with:
          read_key: ${{ secrets.LOCALAZY_READ_KEY }}
          write_key: ${{ secrets.LOCALAZY_WRITE_KEY }}

      - name: Commit new translations
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Updated translations via Localazy
          file_pattern: src/i18n/locales/*.json
