name: Download from Localazy
on:
  workflow_dispatch:
    inputs:
      branch:
        description: "Branch to commit the new translations."
        required: true
        default: "master"

jobs:
  localazy-download:
    name: Download strings from Localazy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}
      
      - name: Download Localazy
        uses: localazy/download@v1
        with:
          read_key: ${{ secrets.LOCALAZY_READ_KEY }}
          write_key: ${{ secrets.LOCALAZY_WRITE_KEY }}

      - name: Commit new translations
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Updated translations via Localazy
          branch: ${{ github.event.inputs.branch }}
          file_pattern: src/i18n/locales/*.json
