name: check pull requests
on:
  pull_request:

jobs:
  check:
    name: check pull request
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: check translations
        uses: dorny/paths-filter@v2
        id: changes
        with:
          list-files: shell
          filters: |
            translations:
              - "src/i18n/locales/*.json"

      - name: comment on pr
        if: steps.changes.outputs.translations == 'true'
        uses: thollander/actions-comment-pull-request@master
        with:
          message: |
            Thank you for your pull request.
            Please remove your translations. Change only the `en.json`. 
            If this pull request is in the `main` branch, it can be translated via localazy.

            Please remove following files
            ```
            ${{ steps.changes.outputs.translations_files }}
            ```
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
