name: check pull requests
on:
  pull_request:

jobs:
  check:
    name: check pull request
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: check translations
        uses: dorny/paths-filter@v2
        id: changes
        with:
          list-files: json
          filters: |
            translations:
              - "src/i18n/locales/!(en)*.json"

      - name: format files output
        if: steps.changes.outputs.translations == 'true'
        id: files-output
        run: |
          files=$(node -e 'console.log("+ " + JSON.parse(`${{ steps.changes.outputs.translations_files }}`).join("\n+ "))')
          echo ::set-output files="${files}"

      - name: comment on pull request
        if: steps.changes.outputs.translations == 'true'
        uses: thollander/actions-comment-pull-request@master
        with:
          message: |
            Thank you for your pull request.
            Please remove your translations. Change only the `en.json` if necessary. 
            If this pull request is merged into the `main` branch, it can be translated via localazy.

            Please remove following files
            ```diff
            ${{ steps.files-output.outputs.files }}
            ```
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: check if failed
        if: steps.changes.outputs.translations == 'true'
        run: |
          echo "only change en.json"
          exit 1
