name: update translations
on:
  push:
    branches:
      - "master"
  schedule:
    - cron: '35 17 * * *'
  workflow_dispatch:

jobs:
  update-translations:
    name: update translations
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}

      - name: download
        uses: localazy/download@v1
        with:
          read_key: ${{ secrets.LOCALAZY_READ_KEY }}
          write_key: ${{ secrets.LOCALAZY_WRITE_KEY }}

      - name: push
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Updated translations via Localazy
          file_pattern: src/i18n/locales/*.json
          commit_author: ""
          commit_user_name: noctera
          commit_user_email: vocascan@gmail.com

      - name: upload
        uses: localazy/upload@v1
        with:
          read_key: ${{ secrets.LOCALAZY_READ_KEY }}
          write_key: ${{ secrets.LOCALAZY_WRITE_KEY }}
